const courseData = [
  {
    name: "Noorani Qaida",
    image: "/assets/alhaseeb-course-0.png",
    description:
      "Norani Qaida is the first step in Quran learning, easing recitation with correct pronunciation, Arabic letters, and tajweed mastery.",
    price: 40,
    tutor: "Hafiz Hamad Raza Chisti",
    additionalDetails: [
      "Arabic Alphabet Recognition",
      "Tajweed Rules",
      "Word Formation & Fluency",
      "Correct Pronunciation & Harakat",
      "Preparation for Quran Reading",
      "Strengthens Tajweed Application",
      "Boosts Memorization Skills",
      "Builds Confidence in Recitation",
      "Prepares for Advanced Quranic Studies",
      "Vowels",
      "Shaddah Madd – Lengthening",
      "AlifulWasl rules",
    ],
    secondaryImg: "/assets/alhaseeb-secondary-img-0.png",
  },
  {
    name: "Quran Reciatation",
    image: "/assets/alhaseeb-course-1.png",
    description:
      "Learn how to Recite Quran correctly easier and faster than ever with professional Quran tutors.",
    price: 50,
    tutor: "Hafiz Hamad Raza Chisti",
    additionalDetails: [
      "The Holy Quran is the last sacred book and the powerful word of Allah",
      "It is the duty of every Muslim to read the Holy Quran with Tajweed",
      "We have designed comprehensive Quran with Tajweed Course for kids and adults (male and females)",
      "Our tutors are experienced online Quran teachers",
      "Our course is for all ages and genders",
      "Some parents think Quran reading with Tajweed rules is very difficult - this is not true",
      "Learning Quran with Tajweed is actually very easy",
      "Students should first complete the Basic Noorani Qaida Course",
      "After Noorani Qaida, students can start reading Quran easily",
    ],
    secondaryImg: "/assets/alhaseeb-secondary-img-1.png",
  },
  {
    name: "Quran Memorization",
    image: "/assets/alhaseeb-course-2.png",
    description:
      "Learn Quran memorization & Become a Hafiz/Hafiz of the Holy Quran through live memorizing classes.",
    price: 70,
    tutor: "Hafiz Hamad Raza Chisti",
    additionalDetails: [
      "Do you or your child aspire to become a Hafiz of the Quran?",
      "Our Online Hifz Quran Course is designed for dedicated students",
      "Memorize the Quran with proper Tajweed and consistent revision",
      "Structured Hifz program with one-on-one sessions",
      "Experienced male and female Quran teachers available",
      "Personalized memorization plans based on your learning pace",
      "Regular revision (Muraja’ah) to retain memorized portions",
      "Tajweed integration from day one for correct recitation",
      "Progress tracking and weekly reports to keep you motivated",
    ],
    secondaryImg: "/assets/alhaseeb-secondary-img-2.png",
  },
  {
    name: "Quran Tafseer",
    image: "/assets/alhaseeb-course-3.png",
    description:
      "Learn Quran Tafseer online and better understand the Quran with the best Islam & Quran scholars.",
    price: 70,
    tutor: "Hafiz Hamad Raza Chisti",
    additionalDetails: [
      "We offer a Translation of Quran Course for male and female students",
      "Learn to translate the Quran with experienced online tutors",
      "Our course is suitable for all ages and genders",
      "Some parents think learning Quran translation is difficult - this is not true",
      "Translation learning is actually very easy with our method",
      "The key is to focus on understanding the meanings",
      "Gradual progression leads students to complete understanding",
      "Perfect for students seeking deeper Quran comprehension",
    ],
    secondaryImg: "/assets/alhaseeb-secondary-img-3.png",
  },
  {
    name: "Quran with Tajweed",
    image: "/assets/alhaseeb-course-4.png",
    description:
      "Read the Holy Quran with correct pronunciation. Get equipped with the learning of the Quran from professional and qualified Quran tutors.",
    price: 70,
    tutor: "Hafiz Hamad Raza Chisti",
    additionalDetails: [
      "Learn Quran recitation with proper Arabic accent",
      "Master exercises for Arabic alphabets from their correct origins (makhaarij)",
      "Practice recitation with both Hadar (fast) and Tarteel (slow) styles",
      "Understand how letters change their forms in the Quranic text",
      "Learn proper stretching of harakaat (vowel sounds)",
      "dentify places where recitation should be stopped or continued",
      "Study rules of Izhar, Ikhfa, Idgham and Iqlab",
      "Master rules of Izhar-e-shafawi, Ikhfa-e-shafawi, Idgham-e-shafawi",
      "Complete practical exercises with Tajweed rules",
      "Gain ability to read Holy Quran with correct pronunciation after course completion",
      "Receive instruction from professional, qualified Quran tutors",
    ],
    secondaryImg: "/assets/alhaseeb-secondary-img-4.png",
  },
  {
    name: "Basic Islamic Course",
    image: "/assets/alhaseeb-course-5.png",
    description:
      "Learn the Islam from basic, get comfertable with the teaching of quran and its rules.",
    price: 50,
    tutor: "Hafiz Hamad Raza Chisti",
    additionalDetails: [
      "Basic Aqaa’id: Covers Allah, Angels, Holy books, Holy prophets, Qiyamah, Jannat, and Jahannam",
      "5 Pillars of Islam: Kalima, Prayer, Fasting, Zakat, and Hajj",
      "Faith: Includes Imaan-e-Mufassil and Imaan-e-Mujmal",
      "Taharah: Teaches Wudhu and Ghusal purification methods",
      "Salah Training: Importance of Salah and practice of five daily prayers (Azaan, prayer names/timings, Fard, Wajib, Sunnat, Nafal)",
      "Special Prayers: Method of Jumuah, Funeral, and Eid Prayers",
      "Daily Du’as: For increasing knowledge, drinking milk, looking in mirror, after sneezing, entering house, and entering toilet",
      "Memorization: Small Surahs, Six Kalemas, Ayah-tul-Kursi, Dua-e-Qunoot, and Islamic months",
      "Sunnah: Actions and teachings of the Holy Prophet Muhammad (PBUH)",
      "Islamic Manners: Proper ways of eating, drinking, sleeping, sneezing, thanking, and giving Salam",
      "Moral Guidance: Dangers of lying and blessings of truthfulness",
    ],
    secondaryImg: "/assets/alhaseeb-secondary-img-5.png",
  },
];

module.exports = { data: courseData };
